using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace AutoResult;

[Generator]
public sealed class AutoResultGenerator : IIncrementalGenerator
{
    // ── Types emitted into every consuming project ───────────────────────────
    private const string CoreTypesSource = @"// <auto-generated by AutoResult.Generator/>
#nullable enable
using System;
using System.Threading.Tasks;

namespace AutoResult
{
    /// <summary>Represents the result of an operation that can succeed with a value or fail with an exception.</summary>
    public readonly struct Result<T>
    {
        private readonly T? _value;
        private readonly Exception? _error;

        public bool IsSuccess { get; }
        public bool IsFailure => !IsSuccess;

        public T Value => IsSuccess ? _value! : throw new InvalidOperationException(""Result is a failure. Check IsSuccess before accessing Value."");
        public Exception Error => !IsSuccess ? _error! : throw new InvalidOperationException(""Result is a success. Check IsFailure before accessing Error."");

        private Result(bool isSuccess, T? value, Exception? error)
        {
            IsSuccess = isSuccess;
            _value    = value;
            _error    = error;
        }

        public static Result<T> Ok(T value) => new Result<T>(true, value, null);
        public static Result<T> Fail(Exception error) => new Result<T>(false, default, error ?? throw new ArgumentNullException(nameof(error)));
        public static Result<T> Fail(string message) => Fail(new Exception(message));

        public static implicit operator Result<T>(T value)         => Ok(value);
        public static implicit operator Result<T>(Exception error)  => Fail(error);

        public override string ToString() => IsSuccess ? $""Ok({_value})"" : $""Fail({_error?.Message})"";
    }

    /// <summary>Represents the result of an operation that can succeed with a value or fail with a typed error.</summary>
    public readonly struct Result<T, TError>
    {
        private readonly T?      _value;
        private readonly TError? _error;

        public bool IsSuccess { get; }
        public bool IsFailure => !IsSuccess;

        public T      Value => IsSuccess  ? _value! : throw new InvalidOperationException(""Result is a failure."");
        public TError Error => !IsSuccess ? _error! : throw new InvalidOperationException(""Result is a success."");

        private Result(bool isSuccess, T? value, TError? error)
        {
            IsSuccess = isSuccess;
            _value    = value;
            _error    = error;
        }

        public static Result<T, TError> Ok(T value)       => new Result<T, TError>(true,  value,   default);
        public static Result<T, TError> Fail(TError error) => new Result<T, TError>(false, default, error);

        public static implicit operator Result<T, TError>(T      value) => Ok(value);
        public static implicit operator Result<T, TError>(TError error) => Fail(error);

        public override string ToString() => IsSuccess ? $""Ok({_value})"" : $""Fail({_error})"";
    }

    /// <summary>Represents the absence of a meaningful value (for void-returning methods wrapped by [TryWrap]).</summary>
    public readonly struct Unit : IEquatable<Unit>
    {
        public static readonly Unit Value = default;
        public bool Equals(Unit other) => true;
        public override bool Equals(object? obj) => obj is Unit;
        public override int  GetHashCode() => 0;
        public override string ToString()  => ""()"";
        public static bool operator ==(Unit left, Unit right) => true;
        public static bool operator !=(Unit left, Unit right) => false;
    }

    /// <summary>Extension methods for Result&lt;T&gt; and Result&lt;T, TError&gt;.</summary>
    public static class ResultExtensions
    {
        public static Result<TOut> Map<T, TOut>(
            this Result<T> result, Func<T, TOut> mapper)
            => result.IsSuccess
                ? Result<TOut>.Ok(mapper(result.Value))
                : Result<TOut>.Fail(result.Error);

        public static Result<TOut, TError> Map<T, TOut, TError>(
            this Result<T, TError> result, Func<T, TOut> mapper)
            => result.IsSuccess
                ? Result<TOut, TError>.Ok(mapper(result.Value))
                : Result<TOut, TError>.Fail(result.Error);

        public static Result<TOut> Bind<T, TOut>(
            this Result<T> result, Func<T, Result<TOut>> binder)
            => result.IsSuccess ? binder(result.Value) : Result<TOut>.Fail(result.Error);

        public static Result<TOut, TError> Bind<T, TOut, TError>(
            this Result<T, TError> result, Func<T, Result<TOut, TError>> binder)
            => result.IsSuccess ? binder(result.Value) : Result<TOut, TError>.Fail(result.Error);

        public static TOut Match<T, TOut>(
            this Result<T> result,
            Func<T, TOut> onSuccess,
            Func<Exception, TOut> onFailure)
            => result.IsSuccess ? onSuccess(result.Value) : onFailure(result.Error);

        public static TOut Match<T, TError, TOut>(
            this Result<T, TError> result,
            Func<T, TOut> onSuccess,
            Func<TError, TOut> onFailure)
            => result.IsSuccess ? onSuccess(result.Value) : onFailure(result.Error);

        public static Result<T> OnSuccess<T>(this Result<T> result, Action<T> action)
        {
            if (result.IsSuccess) action(result.Value);
            return result;
        }

        public static Result<T, TError> OnSuccess<T, TError>(
            this Result<T, TError> result, Action<T> action)
        {
            if (result.IsSuccess) action(result.Value);
            return result;
        }

        public static Result<T> OnFailure<T>(this Result<T> result, Action<Exception> action)
        {
            if (result.IsFailure) action(result.Error);
            return result;
        }

        public static Result<T, TError> OnFailure<T, TError>(
            this Result<T, TError> result, Action<TError> action)
        {
            if (result.IsFailure) action(result.Error);
            return result;
        }

        public static async System.Threading.Tasks.Task<Result<TOut>> MapAsync<T, TOut>(
            this System.Threading.Tasks.Task<Result<T>> resultTask, Func<T, TOut> mapper)
        {
            var result = await resultTask.ConfigureAwait(false);
            return result.Map(mapper);
        }

        public static async System.Threading.Tasks.Task<Result<TOut>> BindAsync<T, TOut>(
            this System.Threading.Tasks.Task<Result<T>> resultTask, Func<T, Result<TOut>> binder)
        {
            var result = await resultTask.ConfigureAwait(false);
            return result.Bind(binder);
        }

        public static async System.Threading.Tasks.Task<TOut> MatchAsync<T, TOut>(
            this System.Threading.Tasks.Task<Result<T>> resultTask,
            Func<T, TOut> onSuccess,
            Func<Exception, TOut> onFailure)
        {
            var result = await resultTask.ConfigureAwait(false);
            return result.Match(onSuccess, onFailure);
        }
    }

    /// <summary>
    /// Place on a <c>partial</c> class to generate <c>Try*()</c> wrappers for all
    /// public methods — sync, async, and void-returning are all handled.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class TryWrapAttribute : Attribute { }
}
";

    // ── Diagnostics ─────────────────────────────────────────────────────────
    private static readonly DiagnosticDescriptor AR001 = new(
        id: "AR001",
        title: "[TryWrap] requires a partial class",
        messageFormat: "'{0}' has [TryWrap] but is not declared as partial. Add the 'partial' modifier to enable Try*() method generation.",
        category: "AutoResult",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AR002 = new(
        id: "AR002",
        title: "No wrappable methods found",
        messageFormat: "'{0}' has [TryWrap] but has no public instance methods to wrap. Add public methods to generate Try*() wrappers.",
        category: "AutoResult",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    // ── Data models ──────────────────────────────────────────────────────────
    private sealed class MethodInfo
    {
        public string Name         { get; set; } = "";
        public string ReturnKind   { get; set; } = ""; // "sync" | "async" | "void" | "async-void"
        public string ReturnTypeFqn { get; set; } = ""; // inner T (for Result<T>), or "Unit"
        public string ParamList    { get; set; } = ""; // "int id, string name"
        public string ArgList      { get; set; } = ""; // "id, name"
    }

    private sealed class WrapperInfo
    {
        public string ClassFqn          { get; set; } = "";
        public string ClassNamespace     { get; set; } = "";
        public string ClassName          { get; set; } = "";
        public bool   IsPartial          { get; set; }
        public bool   HasMethods         { get; set; }
        public List<MethodInfo> Methods  { get; set; } = new();
    }

    // ── Initialize ───────────────────────────────────────────────────────────
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Always emit the core types
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("AutoResult.Core.g.cs", CoreTypesSource));

        // Find [TryWrap] classes
        var wrappers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoResult.TryWrapAttribute",
                predicate: static (n, _) => n is ClassDeclarationSyntax,
                transform: TransformClass)
            .Where(x => x is not null)
            .Select((x, _) => x!);

        context.RegisterSourceOutput(wrappers, GenerateWrappers);
    }

    // ── Transform ────────────────────────────────────────────────────────────
    private static WrapperInfo? TransformClass(
        GeneratorAttributeSyntaxContext ctx,
        CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;

        var typeDecl = (ClassDeclarationSyntax)ctx.TargetNode;
        bool isPartial = typeDecl.Modifiers.Any(SyntaxKind.PartialKeyword);

        var methods = new List<MethodInfo>();

        if (isPartial)
        {
            foreach (var member in typeSymbol.GetMembers())
            {
                ct.ThrowIfCancellationRequested();
                if (member is not IMethodSymbol method) continue;
                if (method.IsStatic || method.DeclaredAccessibility != Accessibility.Public) continue;
                if (method.MethodKind != MethodKind.Ordinary) continue;
                if (method.Name.StartsWith("Try")) continue; // don't wrap already-wrapped methods

                var info = BuildMethodInfo(method, ctx.SemanticModel.Compilation);
                if (info != null) methods.Add(info);
            }
        }

        var ns = typeSymbol.ContainingNamespace?.ToDisplayString() ?? "";

        return new WrapperInfo
        {
            ClassFqn       = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            ClassNamespace  = ns,
            ClassName       = typeSymbol.Name,
            IsPartial       = isPartial,
            HasMethods      = methods.Count > 0,
            Methods         = methods
        };
    }

    private static MethodInfo? BuildMethodInfo(IMethodSymbol method, Compilation compilation)
    {
        var returnType = method.ReturnType;
        string kind;
        string innerFqn;

        // Detect Task<T>, Task, T or void
        if (IsTaskOf(returnType, out var taskArg))
        {
            if (taskArg == null)
            {
                kind     = "async-void"; // Task (no result)
                innerFqn = "global::AutoResult.Unit";
            }
            else
            {
                kind     = "async";
                innerFqn = taskArg.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }
        }
        else if (returnType.SpecialType == SpecialType.System_Void)
        {
            kind     = "void";
            innerFqn = "global::AutoResult.Unit";
        }
        else
        {
            kind     = "sync";
            innerFqn = returnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        var paramList = string.Join(", ", method.Parameters.Select(p =>
            $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}"));
        var argList = string.Join(", ", method.Parameters.Select(p => p.Name));

        return new MethodInfo
        {
            Name          = method.Name,
            ReturnKind    = kind,
            ReturnTypeFqn = innerFqn,
            ParamList     = paramList,
            ArgList       = argList
        };
    }

    // ── Code generation ──────────────────────────────────────────────────────
    private static void GenerateWrappers(SourceProductionContext ctx, WrapperInfo info)
    {
        if (!info.IsPartial)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(AR001, Location.None, info.ClassName));
            return;
        }

        if (!info.HasMethods)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(AR002, Location.None, info.ClassName));
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoResult.Generator/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using AutoResult;");
        sb.AppendLine();

        bool hasNs = !string.IsNullOrEmpty(info.ClassNamespace);
        if (hasNs)
        {
            sb.AppendLine($"namespace {info.ClassNamespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    public partial class {info.ClassName}");
        sb.AppendLine("    {");

        foreach (var m in info.Methods)
        {
            string tryName  = "Try" + m.Name;
            string paramSep = m.ParamList.Length > 0 ? ", " : "";
            string callArgs = m.ArgList;

            switch (m.ReturnKind)
            {
                case "sync":
                    sb.AppendLine($"        /// <summary>Wraps <see cref=\"{m.Name}\"/> and returns a <see cref=\"Result{{T}}\"/> instead of throwing.</summary>");
                    sb.AppendLine($"        public Result<{m.ReturnTypeFqn}> {tryName}({m.ParamList})");
                    sb.AppendLine("        {");
                    sb.AppendLine("            try");
                    sb.AppendLine($"                {{ return Result<{m.ReturnTypeFqn}>.Ok({m.Name}({callArgs})); }}");
                    sb.AppendLine("            catch (Exception ex)");
                    sb.AppendLine($"                {{ return Result<{m.ReturnTypeFqn}>.Fail(ex); }}");
                    sb.AppendLine("        }");
                    break;

                case "void":
                    sb.AppendLine($"        /// <summary>Wraps <see cref=\"{m.Name}\"/> and returns a <see cref=\"Result{{T}}\"/> instead of throwing.</summary>");
                    sb.AppendLine($"        public Result<Unit> {tryName}({m.ParamList})");
                    sb.AppendLine("        {");
                    sb.AppendLine("            try");
                    sb.AppendLine($"            {{ {m.Name}({callArgs}); return Result<Unit>.Ok(Unit.Value); }}");
                    sb.AppendLine("            catch (Exception ex)");
                    sb.AppendLine("            { return Result<Unit>.Fail(ex); }");
                    sb.AppendLine("        }");
                    break;

                case "async":
                    sb.AppendLine($"        /// <summary>Wraps <see cref=\"{m.Name}\"/> and returns a <see cref=\"Result{{T}}\"/> instead of throwing.</summary>");
                    sb.AppendLine($"        public async Task<Result<{m.ReturnTypeFqn}>> {tryName}({m.ParamList})");
                    sb.AppendLine("        {");
                    sb.AppendLine("            try");
                    sb.AppendLine($"                {{ return Result<{m.ReturnTypeFqn}>.Ok(await {m.Name}({callArgs}).ConfigureAwait(false)); }}");
                    sb.AppendLine("            catch (Exception ex)");
                    sb.AppendLine($"                {{ return Result<{m.ReturnTypeFqn}>.Fail(ex); }}");
                    sb.AppendLine("        }");
                    break;

                case "async-void":
                    sb.AppendLine($"        /// <summary>Wraps <see cref=\"{m.Name}\"/> and returns a <see cref=\"Result{{T}}\"/> instead of throwing.</summary>");
                    sb.AppendLine($"        public async Task<Result<Unit>> {tryName}({m.ParamList})");
                    sb.AppendLine("        {");
                    sb.AppendLine("            try");
                    sb.AppendLine($"            {{ await {m.Name}({callArgs}).ConfigureAwait(false); return Result<Unit>.Ok(Unit.Value); }}");
                    sb.AppendLine("            catch (Exception ex)");
                    sb.AppendLine("            { return Result<Unit>.Fail(ex); }");
                    sb.AppendLine("        }");
                    break;
            }

            sb.AppendLine();
        }

        sb.AppendLine("    }");
        if (hasNs) sb.AppendLine("}");

        ctx.AddSource($"AutoResult.{info.ClassName}.g.cs", sb.ToString());
    }

    // ── Helpers ──────────────────────────────────────────────────────────────
    private static bool IsTaskOf(ITypeSymbol type, out ITypeSymbol? typeArg)
    {
        typeArg = null;
        if (type is not INamedTypeSymbol named) return false;

        var def = named.OriginalDefinition.ToDisplayString();
        if (def == "System.Threading.Tasks.Task<TResult>" && named.TypeArguments.Length == 1)
        {
            typeArg = named.TypeArguments[0];
            return true;
        }
        if (def == "System.Threading.Tasks.Task")
            return true;

        return false;
    }
}
